version: '1.0'

services:
  backend:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      # Том ./:/app:
      # ./ - путь на хост-машине.
      # /app - путь внутри контейнера.
      # Монтирует текущую директорию на хосте (./) в директорию /app внутри контейнера (все файлы и подкаталоги в текущей директории на хосте будут доступны в контейнере по пути /app).
      # Позволяет работать с исходными файлами приложения на хосте и видеть изменения в реальном времени внутри контейнера (Полезно для разработки, так как изменения в коде на хосте сразу отражаются внутри контейнера без необходимости пересборки контейнера).
      - /app/node_modules
      # Том /app/node_modules:
      # Создает анонимный том для директории node_modules внутри контейнера (анонимный том означает, что Docker автоматически создаст том и смонтирует его в указанную директорию).
      # Изолирует директорию node_modules от монтирования текущей директории.
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    command: npm run dev:docker
